---
- name: launch instance by ansible
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: launch ec2 instance by ansible
      ec2:
        key_name: mukeshindia
        instance_type: t2.micro
        image: ami-0323c3dd2da7fb37d
        region: us-east-1
        
