
  #must be gather_fact : true then os  when: ansible_os_family == "RedHat" work condition work 
---
- hosts: web1
  gather_facts: true
  become: true  
  #become_method: sudo

  vars:
    project_root: /var/www/html
  tasks:
    - name: Install 
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - apache2
        - git
        - pyhon-pip
      when: ansible_os_family == "CentOS"

    - name: install apache on debian or ubuntu instances
      apt: name={{ item }} state=absent
      apt: name=apache2 state=present
      when: ansible_os_family == "Debian"
      
    - name: location of index file at project reboot
      copy: src=index.html dest={{ project_root }}/index.html owner=apache group=apache mode=0644
      
    - name: Enable appache system reboot and start
      service: name=httpd enabled=yes state=restarted
      when: ansible_os_family == "CentOS"

    - name: Enable appache system reboot and start
      apt: name=apache2 state=restarted
      when: ansible_os_family == "Debian"

