---
- hosts: web1
  gather_facts: false
  #remote_user: ec2_user
 # connection: local
  become: true  
  become_method: sudo

  vars:
    project_root: /var/www/html
  tasks:
    - name: Install httpd latest package
      yum: name=httpd state=latest
      
    - name: location of index file at project 
      copy: src=index.html dest={{ project_root }}/index.html owner=apache group=apache mode=0644
        
      
    - name: Enable appache system reboot
      service: name=httpd enabled=yes

      notify: restart apache
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
     
